IMASD/Nomina2018/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Nomina2018.Models;

namespace Nomina2018.Controllers
{
    public class EmployeesController : Controller
    {
        private Models.Database db = new Models.Database();

        // GET: Employees
        public ActionResult Index(int? pDepto)
        {
            List<Departamento> departamentos = db.Departamento.ToList();
            Departamento todos = new Departamento();
            todos.idDepto = 0;
            todos.nombre = "- Todos los Departamentos";
            departamentos.Insert(0, todos);
            ViewBag.ListaDepartamentos = departamentos;
            ViewBag.Filtro = pDepto ?? 0;

            List<Empleado> empleados = db.Empleado.ToList();
            if (ViewBag.Filtro > 0)
            {
                empleados = empleados.Where(row => row.idDepartamento.Equals(pDepto)).ToList();
            }

            return View(empleados);
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleado.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }

            List<Tabulador> tabulador = db.Tabulador.ToList();
            tabulador = tabulador.Where(row => row.idEmpleado.Equals(id)).ToList();
            ViewBag.TabuladorEmpleado = tabulador;

            return View(empleado);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            List<Departamento> departamentos = db.Departamento.ToList();
            ViewBag.Departamentos = departamentos;
            return View();
        }

        // POST: Employees/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idEmpleado,codigo,nombre,apellidos,direccion,telefono,sueldo,idDepartamento,eliminado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Empleado.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<Departamento> departamentos = db.Departamento.ToList();
            ViewBag.Departamentos = departamentos;
            return View(empleado);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleado.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }

            List<Departamento> departamentos = db.Departamento.ToList();
            ViewBag.Departamentos = departamentos;

            return View(empleado);
        }

        // POST: Employees/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idEmpleado,codigo,nombre,apellidos,direccion,telefono,sueldo,idDepartamento,eliminado")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<Departamento> departamentos = db.Departamento.ToList();
            ViewBag.Departamentos = departamentos;

            return View(empleado);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleado.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado empleado = db.Empleado.Find(id);
            db.Empleado.Remove(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

IMASD/Nomina2018/Controllers/SalaryTabController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nomina2018.Models;

namespace Nomina2018.Controllers
{
    public class SalaryTabController : Controller
    {
        private Models.Database db = new Models.Database();

        // GET: SalaryTab
        public ActionResult Index(int? pEmp, int? pDepto)
        {
            List<Departamento> departamentos = db.Departamento.ToList();
            List<Empleado> empleados = db.Empleado.ToList();
            Departamento todos = new Departamento();
            Empleado todosEmp = new Empleado();
            todos.idDepto = 0;
            todos.nombre = "- Todos los Departamentos";
            todosEmp.idEmpleado = 0;
            todosEmp.nombre = "- Todos los Empleados";
            departamentos.Insert(0, todos);
            empleados.Insert(0, todosEmp);

            ViewBag.ListaDepartamentos = departamentos;
            ViewBag.ListaEmpleados = empleados;
            ViewBag.FiltroEmp = pEmp ?? 0;
            ViewBag.FiltroDepto = pDepto ?? 0;

            List<Tabulador> tabulador = db.Tabulador.OrderBy(item => item.inicioPeriodo).ToList();
            if (ViewBag.FiltroEmp > 0 && ViewBag.FiltroDepto == 0)
            {
                tabulador = tabulador.Where(row => row.idEmpleado.Equals(ViewBag.FiltroEmp)).ToList();
            }
            else if (ViewBag.FiltroEmp == 0 && ViewBag.FiltroDepto > 0)
            {
                tabulador = tabulador.Where(row => row.Empleado.idDepartamento.Equals(ViewBag.FiltroDepto)).ToList();
            }
            else if (ViewBag.FiltroEmp > 0 && ViewBag.FiltroDepto > 0)
            {
                tabulador = tabulador.Where(row => row.idEmpleado.Equals(ViewBag.FiltroEmp) && row.Empleado.idDepartamento.Equals(ViewBag.FiltroDepto)).ToList();
            }

            return View(tabulador);
        }

        // GET: SalaryTab/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tabulador tabulador = db.Tabulador.Find(id);
            if (tabulador == null)
            {
                return HttpNotFound();
            }
            return View(tabulador);
        }

        // GET: SalaryTab/Create
        public ActionResult Create()
        {
            List<Empleado> empleados = db.Empleado.ToList();
            ViewBag.Empleados = empleados;
            Tabulador tabulador = new Tabulador();
            tabulador.idEmpleado = empleados.Select(y => y.idEmpleado).FirstOrDefault();
            return View(tabulador);
        }

        // POST: SalaryTab/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idTabulador,idEmpleado,inicioPeriodo,finPeriodo,sueldo,compensacion,descuento,percepcion,pagado")] Tabulador tabulador)
        {
            if (ModelState.IsValid)
            {
                tabulador.Empleado = db.Empleado.Find(tabulador.idEmpleado);
                db.Tabulador.Add(tabulador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<Empleado> empleados = db.Empleado.ToList();
            ViewBag.Empleados = empleados;

            return View(tabulador);
        }

        // GET: SalaryTab/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tabulador tabulador = db.Tabulador.Find(id);
            if (tabulador == null)
            {
                return HttpNotFound();
            }

            List<Empleado> empleados = db.Empleado.ToList();
            ViewBag.Empleados = empleados;

            return View(tabulador);
        }

        // POST: SalaryTab/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTabulador,idEmpleado,inicioPeriodo,finPeriodo,sueldo,compensacion,descuento,percepcion,pagado")] Tabulador tabulador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tabulador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            List<Empleado> empleados = db.Empleado.ToList();
            ViewBag.Empleados = empleados;

            return View(tabulador);
        }

        // GET: SalaryTab/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tabulador tabulador = db.Tabulador.Find(id);
            if (tabulador == null)
            {
                return HttpNotFound();
            }
            return View(tabulador);
        }

        // POST: SalaryTab/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tabulador tabulador = db.Tabulador.Find(id);
            db.Tabulador.Remove(tabulador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IMASD/Nomina2018/Views/Employees/Create.cshtml
@using Nomina2018.Models
@model Nomina2018.Models.Empleado

@{
    ViewBag.Title = "Empleado - Crear";
    List<Departamento> departamentos = ViewBag.Departamentos;
}

<h2 class="uk-margin-top">Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="uk-form-horizontal">
    <h4>Empleado</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "uk-text-danger" })

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Código:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Nombre:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Apellidos:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Dirección:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Teléfono:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Sueldo base:</label>
        <div class="uk-form-controls">
            @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "uk-input" } })
            @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text">Departamento:</label>
        <div class="uk-form-controls">
            @Html.DropDownListFor(model => model.idDepartamento, departamentos.Select(x => new SelectListItem { Text = x.nombre, Value = x.idDepto.ToString(), Selected = x.idDepto == departamentos.Select(y => y.idDepto).FirstOrDefault() }), new { @class = "uk-select" })
            @Html.ValidationMessageFor(model => model.idDepartamento, "", new { @class = "uk-text-danger" })
        </div>
    </div>

    <div class="uk-margin">
        <label class="uk-form-label" for="form-horizontal-text"> </label>
        &nbsp;&nbsp;&nbsp; <input type="submit" value="Crear" class="uk-button uk-button-primary" />
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", "Employees", null, new { @class = "uk-button uk-button-default" })
</div>

IMASD/Nomina2018/Views/Employees/Delete.cshtml
@model Nomina2018.Models.Empleado

@{
    ViewBag.Title = "Empleado - Eliminar";
}

<h2 class="uk-margin-top">Eliminar</h2>

<h3>¿Estás seguro que deseas eliminarlo?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Código:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codigo)
        </dd>

        <dt>
            Nombre:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            Apellidos:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidos)
        </dd>

        <dt>
            Dirección:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            Teléfono:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            Sueldo base:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sueldo)
        </dd>

        <dt>
            Departamento:
        </dt>

        <dd>
            @Model.Departamento.nombre
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Eliminar" class="uk-button uk-button-primary" /> 
    @Html.ActionLink("Regresar a la lista", "Index", "Employees", null, new { @class = "uk-button uk-button-default" })
</div>
    }
</div>

IMASD/Nomina2018/Views/Employees/Details.cshtml
@using Nomina2018.Models;
@model Nomina2018.Models.Empleado
@{ List<Tabulador> tabulador = ViewBag.TabuladorEmpleado; }

@{
    ViewBag.Title = "Empleado - Detalle";
}

<h2 class="uk-margin-top">Detalle</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Código:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.codigo)
        </dd>

        <dt>
            Nombre:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            Apellidos:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidos)
        </dd>

        <dt>
            Dirección:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            Teléfono:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            Sueldo base:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sueldo)
        </dd>

        <dt>
            Departamento:
        </dt>

        <dd>
            @Model.Departamento.nombre
        </dd>
        <dt></dt>
        <dd>
            @Html.ActionLink("Editar", "Edit", "Employees", new { id = Model.idEmpleado }, new { @class = "uk-button uk-button-primary" })
        </dd>

    </dl>

    @*<button class="uk-button uk-button-primary uk-align-right">Capturar a tabulador</button>*@
    @Html.ActionLink("Capturar a tabulador", "Create", "SalaryTab", null, new { @class = "uk-button uk-button-primary uk-align-right" })
    <table class="uk-table uk-table-striped">
        <thead>
            <tr>
                <th>
                    Periodo
                </th>
                <th>
                    Percepción Bruta
                </th>
                <th>
                    Pago realizado
                </th>
                <th></th>
            </tr>
        </thead>
        @if (tabulador.Count() == 0)
        {
            <tr><td colspan="4"> <i class="glyphicon glyphicon-info-sign"></i> Lista vacía</td></tr>
        }
        @foreach (var item in tabulador)
        {
            <tr>
                <td>
                    @item.inicioPeriodo.Value.ToString("dd MMM yyyy") -
                    @item.finPeriodo.Value.ToString("dd MMM yyyy")
                </td>
                <td>
                    $ @Html.DisplayFor(modelItem => item.percepcion)
                </td>
                <td>
                    @{
                        if (@item.pagado == 0)
                        {
                            <span class="uk-text-danger"> No </span>
                        }
                        else
                        {
                            <span class="uk-text-success"> Sí </span>
                        }
                    }
                </td>
                <td class="uk-text-right">
                    @Html.ActionLink("Editar", "Edit", "SalaryTab", new { id = item.idTabulador }, new { @class = "glyphicon glyphicon-pencil" })
                    | @Html.ActionLink("Detalle", "Details", "SalaryTab", new { id = item.idTabulador }, new { @class = "glyphicon glyphicon-exclamation-sign" })
                    @*| @Html.ActionLink("Eliminar", "Delete", "SalaryTab", new { id = item.idTabulador }, new { @class = "glyphicon glyphicon-trash" })*@
                </td>
            </tr>
        }

    </table>
</div>
<p>
    @Html.ActionLink("Regresar a la lista", "Index", "Employees", null, new { @class = "uk-button uk-button-default" })
</p>

IMASD/Nomina2018/Views/Employees/Edit.cshtml
@using Nomina2018.Models
@model Nomina2018.Models.Empleado

@{
    ViewBag.Title = "Empleado - Editar";
    List<Departamento> departamentos = ViewBag.Departamentos;
}

<h2 class="uk-margin-top">Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="uk-form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "uk-text-danger" })
        @Html.HiddenFor(model => model.idEmpleado)

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Código:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Nombre:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Apellidos:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Dirección:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Teléfono:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Sueldo base:</label>
            <div class="uk-form-controls">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "uk-input" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text">Departamento:</label>
            <div class="uk-form-controls">
                @Html.DropDownListFor(model => model.idDepartamento, departamentos.Select(x => new SelectListItem { Text = x.nombre, Value = x.idDepto.ToString(), Selected = x.idDepto == departamentos.Select(y => y.idDepto).FirstOrDefault() }), new { @class = "uk-select" })
                @Html.ValidationMessageFor(model => model.idDepartamento, "", new { @class = "uk-text-danger" })
            </div>
        </div>

        <div class="uk-margin">
            <label class="uk-form-label" for="form-horizontal-text"> </label>
            &nbsp;&nbsp;&nbsp; <input type="submit" value="Guardar" class="uk-button uk-button-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", "Employees", null, new { @class = "uk-button uk-button-default" })
</div>

IMASD/Nomina2018/Views/Employees/Index.cshtml
@using Nomina2018.Models;
@model List<Nomina2018.Models.Empleado>

@{
    ViewBag.Title = "Empleados";
    List<Departamento> departamentos = ViewBag.ListaDepartamentos;
}

<h2 class="uk-margin-top">Empleados</h2>


<form asp-action="Index" method="get" uk-grid>
    <div class="uk-width-1-5">
        @Html.ActionLink("Crear Nuevo", "Create", "Employees", null, new { @class = "uk-button uk-button-primary" })
    </div>
    <div class="uk-width-1-5"></div>
    <div class="uk-width-2-5">
        @Html.DropDownList("pDepto", departamentos.Select(x => new SelectListItem { Text = x.nombre, Value = x.idDepto.ToString(), Selected = x.idDepto == @ViewBag.Filtro }), new { @class = "uk-input" })
    </div>
    <div class="uk-width-1-5">
        <input type="submit" value="Buscar" class="uk-button uk-button-default uk-width-1-1" />
    </div>
</form>
<table class="uk-table uk-table-striped">
    <thead>
        <tr>
            <th>
                #Código
            </th>
            <th>
                Nombre Completo
            </th>
            <th>
                Contacto
            </th>
            <th>
                Sueldo base
            </th>
            <th>
                Departamento
            </th>
            <th></th>
        </tr>
    </thead>

    @if (Model.Count() == 0)
    {
        <tr><td colspan="6"> <i class="glyphicon glyphicon-info-sign"></i> Lista vacía</td></tr>
    }

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre) @Html.DisplayFor(modelItem => item.apellidos)
            </td>
            <td>
                <span class="glyphicon glyphicon-home"></span> @Html.DisplayFor(modelItem => item.direccion) <br />
                <span class="glyphicon glyphicon-phone"></span> @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                $ @Html.DisplayFor(modelItem => item.sueldo)
            </td>
            <td>
                @item.Departamento.nombre
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", "Employees", new { id = item.idEmpleado }, new { @class = "glyphicon glyphicon-pencil" })
                | @Html.ActionLink("Detalle", "Details", "Employees", new { id = item.idEmpleado }, new { @class = "glyphicon glyphicon-exclamation-sign" })
                | @Html.ActionLink("Eliminar", "Delete", "Employees", new { id = item.idEmpleado }, new { @class = "glyphicon glyphicon-trash" })
            </td>
        </tr>
    }

</table>